"""Your migration message

Revision ID: 6e949a7c69f6
Revises: 987e64cd068e
Create Date: 2024-12-04 05:05:49.352558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e949a7c69f6'
down_revision: Union[str, None] = '987e64cd068e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bug_reports', sa.Column('tab_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bug_reports', 'tab_url')
    # ### end Alembic commands ###
