"""baseline

Revision ID: d32a25bb578d
Revises: 
Create Date: 2025-01-02 15:27:27.274286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32a25bb578d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bug_report_comments', 'bug_report_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bug_report_comments', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('bug_reports', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bug_reports', 'media_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bug_reports', 'modified_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bug_reports', 'modified_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('bug_reports', 'media_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bug_reports', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bug_report_comments', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('bug_report_comments', 'bug_report_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
