"""add_cc_recipients_table

Revision ID: e603b56c19f0
Revises: 6e949a7c69f6
Create Date: 2024-12-16 23:24:57.466548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e603b56c19f0'
down_revision: Union[str, None] = '6e949a7c69f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_report_cc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug_report_id', sa.Integer(), nullable=True),
    sa.Column('cc_recipient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bug_report_id'], ['bug_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cc_recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_report_cc_id'), 'bug_report_cc', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bug_report_cc_id'), table_name='bug_report_cc')
    op.drop_table('bug_report_cc')
    # ### end Alembic commands ###
